### ISSUE TITLE
Is there a way to build on Pull Request and merge on master

### ISSUE THREAD

**Issue by ocefpaf** [BryanSchuetz/jekyll-deploy-gh-pages#23]
Sorry if this a dumb question, I'm new to GH-actions, but is there a way to build on PRs and deploy the site when the PR is merged? So the action can be used as a CI and/or even push to a staging site for inspection?

Looks like the individual build and deploy parts are there but the root entrypoints is the one that is called, right?

**Comment by BryanSchuetz** [comment]
That was my initial thinking, when I split them out—was a while ago though.

The examples in the build and deploy folders use the older Beta syntax...but if you use the new version it should work I think.
