### ISSUE TITLE
Issues building github pages site

### ISSUE THREAD

**Issue by joshuarubin** [BryanSchuetz/jekyll-deploy-gh-pages#3]
Just wondering if you ran into any issues with pages saying (on repo settings page):

> Your site is having problems building: Page build failed.

I have the `.nojekyll` in the root of both my `master` and `gh-pages` branches.

If I push an empty commit to the `gh-pages` branch, things work fine.

**Comment by BryanSchuetz** [comment]
Have to love the amount of detail in the GH-Pages error messaging. 

So, interesting. Your `_config.yml` file is not in the root of your repo? What about your Gemfile?

**Comment by BryanSchuetz** [comment]
I suppose we could add a Source environment variable, pointing to the directory Jekyll lives in.

**Comment by joshuarubin** [comment]
So I'm not running jekyll, I'm using [joshuarubin/hugo-deploy-gh-pages](https://github.com/joshuarubin/hugo-deploy-gh-pages). I got this back from GitHub Support though (and it seems to work):

> Hi Joshua,
>
>Thank you for writing in to GitHub Support.
>
> I see you're part of the Actions beta, and you're trying to trigger a Page build with an Action. That puts you right on the bleeding edge! 😄
>
> Currently that behavior isn't supported, so the official advice is to wait until Actions has been rolled out to everyone and is no longer in beta.
>
> Unofficially, I've heard talk of a somewhat hacky solution where the push back to GitHub, if it’s done with a Personal Access Token for your account, will build the site, but I haven't tried this myself so can't guarantee it.
>
> If there's anything else I can do, give me a shout!
>
> Cheers,
>
> Matt R

**Comment by BryanSchuetz** [comment]
Ahh, I see. Interesting—I haven't had a problem just using the provided `GITHUB_TOKEN`, but good to know.
