### ISSUE TITLE
Support Jekyll 4.x

### ISSUE THREAD

**Issue by koppor** [BryanSchuetz/jekyll-deploy-gh-pages#5]
Currently, the build environment points to ruby 2.3.4: https://github.com/BryanSchuetz/jekyll-deploy-gh-pages/blob/59c8f5f63361271c61d345c387f03ab7fc847e70/Dockerfile#L1

Jekyll 4.0.0, however, requires ruby 2.4.0 (https://jekyllrb.com/news/2019/08/20/jekyll-4-0-0-released/).

**Comment by BryanSchuetz** [comment]
I've updated this action to work with the new version of GHActions. I've also upgraded the ruby used in the dockerfile to 2.4.0
